public class Info {
    static String funcao[]         = {"NOME","TELEFONE","E-MAIL","SEXO"};
	static String entrada[]        = {"DIGITA O NOME","DIGITA O TELEFONE","DIGITA O E-MAIL","DIGITA O SEXO (1-MASCULINO | 2-FEMININO)"};
	static String entradaEdicao[]  = {"DIGITA NOVO NOME","DIGITA NOVO TELEFONE","DIGITA NOVO E-MAIL","DIGITA NOVO SEXO (1-MASCULINO | 2-FEMININO)"};
	static String erros[]          = {"NOME INVALIDO! MINIMO 2 CARACTERES.","TELEFONE INVALIDO! MINIMO 10 OU MAXIMO 11 CARACTERES NUMERICOS.","E-MAIL INVALIDO! MINIMO 10 CARACTERES.","SEXO INVALIDO!"};
}
